[project]
name = "fastarch"
version = "1.0.0"
description = "Package for automatic architecture schemas renderers. Includes FastAPI and Litestar integrations"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.ruff]
fix = true
unsafe-fixes = true
line-length = 120
exclude = ["tests/fastapi/src/*", "tests/litestar/src/*"]

[tool.ruff.format]
quote-style = "preserve"
line-ending = "auto"
docstring-code-format = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "EM",
    "FBT",
    "TRY003",
    "D1",
    "D203",
    "D213",
    "G004",
    "FA",
    "COM812",
    "ISC001",
    "CPY001",
]
external = ["WPS"]

[tool.ruff.lint.isort]
no-lines-before = ["standard-library", "local-folder"]
known-third-party = []
known-local-folder = []
lines-after-imports = 2

[tool.ruff.lint.extend-per-file-ignores]
"tests/*.py" = ["S101", "S311"]

[tool.mypy]
exclude = ["tests/fastapi/", "tests/litestar/"]

[tool.pytest.ini_options]
addopts = "--cov=. --cov-report=term-missing"

[tool.coverage.run]
omit = ["tests/fastapi/*"]

[tool.coverage.report]
exclude_also = ["if typing.TYPE_CHECKING:"]
[dependency-groups]
dev = [
    "auto-typing-final>=0.7.2",
    "fastapi>=0.115.11",
    "hypothesis>=6.137.1",
    "litestar>=2.15.1",
    "mypy>=1.15.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.0",
    "pytest-xdist>=3.6.1",
    "ruff>=0.11.2",
    "wemake-python-styleguide>=1.1.0",
]
