name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  ci:
    uses: template.yaml@main
    with:
      python-version: '["3.12","3.13"]'
    secrets: inherit

  lint2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: wemake-services/wemake-python-styleguide@1.1.0
        with:
          reporter: "github-pr-review"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
