name: Lint and Type Check

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          cache-dependency-glob: "**/pyproject.toml"
      - run: uv python install ${{ fromJSON(inputs.python-version)[0] }}
      - run: just install
      - run: just lint check

  test:
    name: ${{matrix.os}}-${{matrix.python-version}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(inputs.python-version) }}
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          cache-dependency-glob: "**/pyproject.toml"
      - run: uv python install ${{ matrix.python-version }}
      - run: just install
      - run: just test
      - uses: codecov/codecov-action@v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.python-version }}
